services:
  frontend:
    build:
      context: .
      target: wbc-frontend
    container_name: wbc_frontend
    volumes:
      - ./src/frontend:/frontend
      - frontend_modules:/frontend/node_modules
    networks:
      - app-network
    ports:
      - 5000:5000
    command: npm run dev
  backend:
    build:
      context: .
      target: wbc-backend
    container_name: wbc_backend
    volumes:
      - ./src/backend:/backend
      - backend_modules:/backend/node_modules
    networks:
      - app-network
    ports:
      - 3000:3000
    command: npm run dev
  nginx:
    build:
      context: .
      target: wbc-nginx
    container_name: wbc_nginx
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  backend_modules:
  frontend_modules: